### PR TITLE
Merging Adorable master to LMHT master - deploy to live site

### PR DESCRIPTION
**Pull request by kathyoleary**
💚  Deploying Adorable changes to the LMHT live site.

All of these have already been approved through separate PR's on the Adorable site, just deploying now to live site.

### CODE REVIEW

**Comment by ericanaughton** [comment]
I notice that the tags are sometimes bold if they're used in the definition and how to remember sections, but sometimes they are not bold. I think it should be consistent. Letting them all be bold would probably help them stand out a bit.

**Comment by ericanaughton** [comment]
looks good, great job!

**Comment by kathyoleary** [comment]
I just looked through and noticed that the original ones set up had the bold in place.  I'm going to set up a separate PR to clean those up and one other thing I noticed.  So is that a thumbs up for this for now?

**Comment by bigtiger** [comment]
:+1:

**Comment by ericanaughton** [comment]
👍

**Pull request merged**
