### PR TITLE
Added meta translation

### PR DESCRIPTION
**Pull request by mostlybadfly**
In reference to #34 . Added a translation for <meta>

### CODE REVIEW

**Comment by JenEEsquivel** [comment]
@mostlybadfly I think these changes get thumbs up, but want to be sure about a subtle grammar issue.  I think this is correct: "Algunos tipos de información que representa son atributos como nombre y contenido."  But, I want to be certain that "representa" doesn't need to be plural in this context (just double checking).  Otherwise, looks good.

**Comment by mostlybadfly** [comment]
Hi @JenEEsquivel I think in this context the subject of the verb is <meta>  and would take the singular, I was kinda going for "Algunos tipos de información que (<meta>) representa son atributos como nombre y contenido." I do wonder if it would be more clear to have the tag again like that, thoughts?

**Comment by jremsik-gpsw** [comment]
:+1:

**Comment by mostlybadfly** [comment]
Updated to include Spanish character encoding.

**Comment by JenEEsquivel** [comment]
Spanish character encoding :+1: Thank you @mostlybadfly 

@ericanaughton or @jremsik-gpsw 
Observation about what we currently have (first sentence of the English definition):
If we use comparison/analogy (A is to B as X is to Y as metadata is to metalanguage), then the definition is incomplete because it doesn't seem to really/fully define metadata.  It just says it is like metalanguage.  

First sentence currently says: "Metadata is like a metalanguage because it provides a language for how to describe a language."

I suggest incorporating something like this in the first sentence:
"Metalanguage is like metadata in that metalanguage is language about language and metadata is data about data."

Thoughts?

**Comment by mostlybadfly** [comment]
@JenEEsquivel I really like the suggestion, it reads much more nicely and represents the analogy better. :+1:

**Comment by ericanaughton** [comment]
i agree, that makes more sense @JenEEsquivel

**Comment by mostlybadfly** [comment]
@ericanaughton @JenEEsquivel should I add the change to this PR? I can update during my lunch break. Otherwise we can leave this PR for now and make it the next change to do for this file? Thoughts?

**Comment by ericanaughton** [comment]
@mostlybadfly i think it's okay to add it to this PR :) thanks!

**Comment by mostlybadfly** [comment]
@JenEEsquivel it was a little tricky in Spanish but hopefully it flows correctly to match the new English example, thoughts?

**Comment by JenEEsquivel** [comment]
:+1: Looks great @mostlybadfly  (One more question about the definition of Metadata: in the second sentence, should we replace "data" for the word "language?") @ericanaughton @jremsik-gpsw Thoughts?

**Comment by ericanaughton** [comment]
I'm gonna say, let's merge this one now, since the PR is related to Spanish translation.  In the future, we can refine all the English in the whole site, and make a PR just for that. :+1:

**Pull request merged**
