### PR TITLE
Added translation for head

### PR DESCRIPTION
**Pull request by mostlybadfly**
In reference to #36 , adding a translation for <head>

### CODE REVIEW

**Comment by JenEEsquivel** [comment]
@mostlybadfly We are going to use the Spanish encoding for special characters (like á é í ó ú ñ which are available here:  http://www.thesauruslex.com/typo/eng/enghtml.htm#Spanish) in the HTML.  So...

información change to informaci& oacute;n
título change to t& iacute;tulo
Así change to As& eacute;
también change to tambi& eacute;n
está change to est& aacute;

(with no space after the &'s above the special character code)

We aren't sure (who will and) how we are going to make these changes throughout the pages yet.   Happy Thanksgiving

**Comment by JenEEsquivel** [comment]
@mostlybadfly (another I see) and 
Español change to Espa& nacute;ol
Traducción change to Traducci& oacute; n (without the space after the "&" in special character...I added the spaces so github doesn't autoconvert)

**Comment by mostlybadfly** [comment]
thanks @JenEEsquivel , I'll go back and use the encoding for all my translations.  I haven't used this in any. I'll be fixing them around noon today.

**Comment by ericanaughton** [comment]
good work @JenEEsquivel & @mostlybadfly

**Comment by mostlybadfly** [comment]
@JenEEsquivel I have updated the encoding on this translation, thanks!

**Comment by savance-ford** [comment]
:+1:  from Maria

**Comment by JenEEsquivel** [comment]
@mostlybadfly Awesome.  You help is really appreciated.  @SaVanceX Thank you to Maria, too. :+1:

**Pull request merged**
