### PR TITLE
Meta english

### PR DESCRIPTION
**Pull request by ericanaughton**
:cactus: 

ready to go

### CODE REVIEW

**Comment by jremsik-gpsw** [comment]
:+1:

**Comment by kathyoleary** [comment]
:+1:

**Comment by kevinbrianfahy** [comment]
Hey Erica, did it work with me creating a team and adding you as owner? Are you able to merge??

**Comment by ericanaughton** [comment]
hey kevin, yup ive been able to merge everything! thanks a bunch!

**Comment by kevinbrianfahy** [comment]
ok...I noticed you put Kathy as a collaborator. You'll actually want to simply add her to the LMHT Team, and from there give her access as you want. I'm trying to keep everything in one place for organizational purposes. For instance, I deleted Rafa as a collaborator when he accepted my team invite because now he has collaborator access through the team. This way I don't have a long list of collaborators and/or two separate places to view who has access but just one simple file of team where you can view all people, both people with write authority and read only authority
I just sent Kathy an invite to the team, make sure she accepts it, give her write access and then we can delete her as collaborator. I'm doing the same with Chris once he accepts invite to the team.....
Make sense??

**Comment by ericanaughton** [comment]
ok!

**Pull request merged**
